version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies
      - yum -y update
      - yum -y install mysql-devel
      - yum -y install python-devel
      - yum -y install mysql57-devel
      - yum -y install python36-devel
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'