version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies
      - pip install -r requirements.txt
      - apt-get update
      - apt-get install -y jq mysql-client

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'