# Generated by Django 4.0.1 on 2022-09-05 01:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clasification', models.CharField(max_length=50)),
                ('mass', models.IntegerField()),
                ('fall', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            managers=[
                ('meteorites', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ufo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('ufo_shape', models.CharField(blank=True, max_length=50, null=True)),
                ('length_of_encounter_seconds', models.IntegerField()),
                ('described_duration_of_encounter', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            managers=[
                ('encounters', django.db.models.manager.Manager()),
            ],
        ),
    ]
