# Generated by Django 4.0.1 on 2022-09-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0002_alter_ufo_city_alter_ufo_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufo',
            name='length_of_encounter_seconds',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
