# Generated by Django 4.0.1 on 2022-09-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0003_alter_ufo_length_of_encounter_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufo',
            name='length_of_encounter_seconds',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
    ]
